# Generated by Django 4.0.4 on 2022-05-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_diary_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
