# Generated by Django 4.0.4 on 2022-05-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_canvas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_description',
            field=models.CharField(max_length=32767, null=True),
        ),
    ]
